spring:
  application:
    name: tossverification
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:postgresql://localhost:5432/tossverification
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    async:
      request-timeout: 180000

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: env,health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
