version: "3.8"

services:
  postgres-tossverification:
    image: postgres:16
    container_name: tossverification-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tossverification
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_tossverification:/var/lib/postgresql/data

volumes:
  postgres_data_tossverification:
    driver: local
