version: "3.8"

services:
  postgres-adservice:
    image: postgres:16
    container_name: adservice-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: toss-veification
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_toss_verification:/var/lib/postgresql/data

volumes:
  postgres_data_toss_verification:
    driver: local